org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.164
neo_version_range=[21.1.164,)
loader_version_range=[1,)

mod_id=sedna
mod_name=Sedna for Minecraft
mod_license=MIT
mod_authors=Sangar
mod_description=RISC-V Virtual Machine and binary images for computer mods.\n\nThis mod contains a Linux distribution built from the "sedna" branch of the following repository:\n\n  https://github.com/fnuecke/buildroot\n\nThe licenses for the embedded software are embedded in the JAR file containing this mod, inside the "licenses" directory.

semver=1.0.14

curse_project_id=511276
