pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = "https://maven.neoforged.net/releases" }
    }
}

rootProject.name = "sedna-1.21.1-neoforge"
final def isWindows = System.getProperty("os.name").toLowerCase().contains("windows")

def substituteLocal = { final directoryName, final libraryName ->
    if (directoryName == "buildroot" && isWindows) {
        return
    }

    final def path = new File("../${directoryName}")
    if (path.exists()) {
        println("Found local [${directoryName}] project, substituting...")
        includeBuild(path) {
            dependencySubstitution {
                substitute module(libraryName) using project(':')
            }
        }
    }
}

substituteLocal("ceres", "li.cil.ceres:ceres")
substituteLocal("sedna", "li.cil.sedna:sedna")
substituteLocal("buildroot", "li.cil.sedna:sedna-buildroot")
