modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${jar_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "${mod_authors}"
description = '''
${mod_description}
'''

[[dependencies.sedna]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.sedna]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[features.sedna]
javaVersion = "[21,)"
